#
###################################
# Site wide configuration
####################################
#
title: Dalimunthe Blog
email: rasyid.dalimunthe@gmail.com
description: Anything I Want and I Care.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: http://dalimunthe.github.io

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Rasyid A Dalimunthe
  avatar: avatar.jpg
  job: "Spatial in Code"
  bio: "i do some html, php and python language, sometimes make some maps sometimes i develop new things"
  email: rasyid.dalimunthe@gmail.com
  disqus-shortname: rssyid
  twitter: rssyid
  facebook: rasyid.ahyar
  google:
    plus: +RasyidAhyarDalimunthe
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dalimunthe
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: rssyid
  xing: #username
  instagram: rssyid
  lastfm: earbutt
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: rotttenone
  soundcloud: rasyid-ahyar
  weibo: #username
  flickr: #username
  codepen: #username
